module.exports = {
    CURATED_REVIEWS: [
    {
        "id": "rev_hiep_si_mat_na_my_th_huyen_thoai_12_con_giap_1MmeiWOtUuc",
        "yt": "1MmeiWOtUuc",
        "title": "Hiệp Sĩ Mặt Nạ MY-TH: Huyền Thoại 12 Con Giáp",
        "origin_title": "Kamen Rider MY-TH",
        "slug": "hiep-si-mat-na-my-th-huyen-thoai-12-con-giap",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260907/hiep-si-mat-na-my-th-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 31492,
        "likes": 43311,
        "comments_count": 118,
        "caption": "Review chi tiết siêu phẩm Hiệp Sĩ Mặt Nạ MY-TH: Huyền Thoại 12 Con Giáp (Kamen Rider MY-TH).",
        "categories": [
            "Hành Động",
            "Phiêu Lưu",
            "Khoa Học",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_tho_san_giac_thu_omegahorn_bWNZ84d2b_o",
        "yt": "bWNZ84d2b_o",
        "title": "Thợ Săn Giác Thú Omegahorn",
        "origin_title": "KakuseiHunter Omegahorn",
        "slug": "tho-san-giac-thu-omegahorn",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260726/tho-san-giac-thu-omegahorn-poster.webp",
        "year": "2026",
        "rating": "2.8",
        "views": 50643,
        "likes": 38163,
        "comments_count": 137,
        "caption": "Review chi tiết siêu phẩm Thợ Săn Giác Thú Omegahorn (KakuseiHunter Omegahorn).",
        "categories": [
            "Chính Kịch",
            "Phiêu Lưu",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_tien_nghich_Q5bvFUEPRuE",
        "yt": "Q5bvFUEPRuE",
        "title": "Tiên Nghịch",
        "origin_title": "Renegade Immortal",
        "slug": "tien-nghich",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260720/tien-nghich-poster.webp",
        "year": "2023",
        "rating": "4.1",
        "views": 21744,
        "likes": 44990,
        "comments_count": 147,
        "caption": "Review chi tiết siêu phẩm Tiên Nghịch (Renegade Immortal).",
        "categories": [
            "Chính Kịch",
            "Hoạt Hình",
            "Hành Động",
            "Phiêu Lưu"
        ]
    },
    {
        "id": "rev_buoc_duong_cung_Ey5VRdEGhNI",
        "yt": "Ey5VRdEGhNI",
        "title": "Bước Đường Cùng",
        "origin_title": "Bronson",
        "slug": "buoc-duong-cung",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260927/buoc-duong-cung-poster.webp",
        "year": "2009",
        "rating": "3.5",
        "views": 37764,
        "likes": 24134,
        "comments_count": 363,
        "caption": "Review chi tiết siêu phẩm Bước Đường Cùng (Bronson).",
        "categories": [
            "Chính Kịch",
            "Hành Động",
            "Hình Sự"
        ]
    },
    {
        "id": "rev_trum_cuoi_hoang_da_gia_lam_trum_cuoi_hoang_da_xuat_hien_phan_2_Y_G0A8ohFLo",
        "yt": "Y_G0A8ohFLo",
        "title": "Trùm Cuối Hoang Dã Giá Lâm! / Trùm Cuối Hoang Dã Xuất Hiện! (Phần 2)",
        "origin_title": "A Wild Last Boss Appeared! (Season 2)",
        "slug": "trum-cuoi-hoang-da-gia-lam-trum-cuoi-hoang-da-xuat-hien-phan-2",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260927/trum-cuoi-hoang-da-gia-lam-trum-cuoi-hoang-da-xuat-hien-phan-2-poster.webp",
        "year": "2026",
        "rating": "3.6",
        "views": 18059,
        "likes": 40602,
        "comments_count": 118,
        "caption": "Review chi tiết siêu phẩm Trùm Cuối Hoang Dã Giá Lâm! / Trùm Cuối Hoang Dã Xuất Hiện! (Phần 2) (A Wild Last Boss Appeared! (Season 2)).",
        "categories": [
            "Hoạt Hình",
            "Hành Động",
            "Phiêu Lưu",
            "Khoa Học",
            "Viễn Tưởng",
            "Chính Kịch"
        ]
    },
    {
        "id": "rev_truyen_kinh_di_my_phan_13_nLJR2twdK00",
        "yt": "nLJR2twdK00",
        "title": "Truyện Kinh Dị Mỹ (Phần 13)",
        "origin_title": "American Horror Story (Season 13)",
        "slug": "truyen-kinh-di-my-phan-13",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260927/truyen-kinh-di-my-phan-13-poster.webp",
        "year": "2026",
        "rating": "4.0",
        "views": 69480,
        "likes": 49908,
        "comments_count": 311,
        "caption": "Review chi tiết siêu phẩm Truyện Kinh Dị Mỹ (Phần 13) (American Horror Story (Season 13)).",
        "categories": [
            "Chính Kịch",
            "Bí Ẩn",
            "Khoa Học",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_chim_vao_mat_em_phan_1_sA7Eayl5ff8",
        "yt": "sA7Eayl5ff8",
        "title": "Chìm Vào Mắt Em (Phần 1)",
        "origin_title": "Dive into You (Season 1)",
        "slug": "chim-vao-mat-em-phan-1",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260927/chim-vao-mat-em-phan-1-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 49218,
        "likes": 11420,
        "comments_count": 248,
        "caption": "Review chi tiết siêu phẩm Chìm Vào Mắt Em (Phần 1) (Dive into You (Season 1)).",
        "categories": [
            "Hài Hước",
            "Chính Kịch",
            "Khoa Học",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_nhat_au_xuan_RAzoSbzSHd4",
        "yt": "RAzoSbzSHd4",
        "title": "Nhất Âu Xuân",
        "origin_title": "Spring Of The Blade",
        "slug": "nhat-au-xuan",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260917/nhat-au-xuan-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 94020,
        "likes": 20834,
        "comments_count": 299,
        "caption": "Review chi tiết siêu phẩm Nhất Âu Xuân (Spring Of The Blade).",
        "categories": [
            "Chính Kịch",
            "Gia Đình"
        ]
    },
    {
        "id": "rev_lan_huong_nhu_co_HXxzKhKBwAM",
        "yt": "HXxzKhKBwAM",
        "title": "Lan Hương Như Cố",
        "origin_title": "Against The Current",
        "slug": "lan-huong-nhu-co",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260912/lan-huong-nhu-co-poster.webp",
        "year": "2026",
        "rating": "4.5",
        "views": 47002,
        "likes": 19462,
        "comments_count": 79,
        "caption": "Review chi tiết siêu phẩm Lan Hương Như Cố (Against The Current).",
        "categories": [
            "Chính Kịch",
            "Gia Đình",
            "Cổ Trang",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_cau_va_to_la_hai_thai_cuc_doi_lap_seihantai_na_kimi_to_boku_phan_2_pbeDDMlT0rI",
        "yt": "pbeDDMlT0rI",
        "title": "Cậu Và Tớ Là Hai Thái Cực Đối Lập (Seihantai na Kimi to Boku) (Phần 2)",
        "origin_title": "You and I Are Polar Opposites (Season 2)",
        "slug": "cau-va-to-la-hai-thai-cuc-doi-lap-seihantai-na-kimi-to-boku-phan-2",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260706-1/a7325eb2658ffe5ad2d8a782910f5542.jpg",
        "year": "2026",
        "rating": "4.2",
        "views": 87551,
        "likes": 49734,
        "comments_count": 298,
        "caption": "Review chi tiết siêu phẩm Cậu Và Tớ Là Hai Thái Cực Đối Lập (Seihantai na Kimi to Boku) (Phần 2) (You and I Are Polar Opposites (Season 2)).",
        "categories": [
            "Chính Kịch",
            "Hài Hước",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_muc_than_ky_VPDwO3G3tgQ",
        "yt": "VPDwO3G3tgQ",
        "title": "Mục Thần Ký",
        "origin_title": "Tales Of Herding Gods",
        "slug": "muc-than-ky",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20241028-1/33727a6c4cec6ab127dbb0092bc99c9e.jpg",
        "year": "2024",
        "rating": "4.1",
        "views": 29114,
        "likes": 25645,
        "comments_count": 423,
        "caption": "Review chi tiết siêu phẩm Mục Thần Ký (Tales Of Herding Gods).",
        "categories": [
            "Phiêu Lưu",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_than_y_co_dai_o_do_thi_do_thi_co_tien_y_A_ikX4OhoH4",
        "yt": "A_ikX4OhoH4",
        "title": "Thần Y Cổ Đại Ở Đô Thị (Đô Thị Cổ Tiên Y)",
        "origin_title": "Urban Miracle Doctor",
        "slug": "than-y-co-dai-o-do-thi-do-thi-co-tien-y",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20241018-1/422e01866d2bfcb0adfd4ae2a31ef32f.jpg",
        "year": "2024",
        "rating": "4.3",
        "views": 92147,
        "likes": 19568,
        "comments_count": 150,
        "caption": "Review chi tiết siêu phẩm Thần Y Cổ Đại Ở Đô Thị (Đô Thị Cổ Tiên Y) (Urban Miracle Doctor).",
        "categories": [
            "Hành Động",
            "Phiêu Lưu",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_nguoi_tuyet_sat_nhan_brOt5TJViCY",
        "yt": "brOt5TJViCY",
        "title": "Người Tuyết Sát Nhân",
        "origin_title": "Jack Frost",
        "slug": "nguoi-tuyet-sat-nhan",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260927/nguoi-tuyet-sat-nhan-poster.webp",
        "year": "1997",
        "rating": "2.5",
        "views": 94202,
        "likes": 19378,
        "comments_count": 275,
        "caption": "Review chi tiết siêu phẩm Người Tuyết Sát Nhân (Jack Frost).",
        "categories": [
            "Viễn Tưởng",
            "Kinh Dị",
            "Hài Hước",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_ban_cau_co_1986_mfvgWqJ2vfc",
        "yt": "mfvgWqJ2vfc",
        "title": "Bàn Cầu Cơ",
        "origin_title": "Witchboard",
        "slug": "ban-cau-co-1986",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260927/ban-cau-co-1986-poster.webp",
        "year": "1986",
        "rating": "2.9",
        "views": 34496,
        "likes": 38853,
        "comments_count": 262,
        "caption": "Review chi tiết siêu phẩm Bàn Cầu Cơ (Witchboard).",
        "categories": [
            "Kinh Dị",
            "Bí Ẩn",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_vao_ma_gioi_roi_day_irumakun_phan_4_6Lo1DUCY9nY",
        "yt": "6Lo1DUCY9nY",
        "title": "Vào Ma Giới Rồi Đấy! Iruma-kun (Phần 4)",
        "origin_title": "Welcome To Demon School! Iruma-kun (Season 4)",
        "slug": "vao-ma-gioi-roi-day-irumakun-phan-4",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260407-1/c4b0b33444924bf81ca7bfe6081e4ef7.jpg",
        "year": "2026",
        "rating": "4.1",
        "views": 92378,
        "likes": 37190,
        "comments_count": 151,
        "caption": "Review chi tiết siêu phẩm Vào Ma Giới Rồi Đấy! Iruma-kun (Phần 4) (Welcome To Demon School! Iruma-kun (Season 4)).",
        "categories": [
            "Hài Hước",
            "Khoa Học",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_song_menh_coi_hoang_tuyen_L3KeCXykpFw",
        "yt": "L3KeCXykpFw",
        "title": "Song Mệnh Cõi Hoàng Tuyền",
        "origin_title": "Daemons Of The Shadow Realm",
        "slug": "song-menh-coi-hoang-tuyen",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260406-1/3c48ae9098dc344eb0dd90b9ed136bcd.jpg",
        "year": "2026",
        "rating": "4.3",
        "views": 32834,
        "likes": 15115,
        "comments_count": 107,
        "caption": "Review chi tiết siêu phẩm Song Mệnh Cõi Hoàng Tuyền (Daemons Of The Shadow Realm).",
        "categories": [
            "Hành Động",
            "Khoa Học",
            "Phiêu Lưu",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_rap_xiec_hoa_huong_duong_W93ZGwcNfh8",
        "yt": "W93ZGwcNfh8",
        "title": "Rạp Xiếc Hoa Hướng Dương",
        "origin_title": "GROW UP SHOW -Sunflower Circus-",
        "slug": "rap-xiec-hoa-huong-duong",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260708/rap-xiec-hoa-huong-duong-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 16043,
        "likes": 13991,
        "comments_count": 36,
        "caption": "Review chi tiết siêu phẩm Rạp Xiếc Hoa Hướng Dương (GROW UP SHOW -Sunflower Circus-).",
        "categories": [
            "Hoạt Hình",
            "Hài Hước",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_nhung_nguoi_ban_ma_phan_3_kaOCCmwAhGc",
        "yt": "kaOCCmwAhGc",
        "title": "Những Người Bạn Ma (Phần 3)",
        "origin_title": "Ghosts (Season 3)",
        "slug": "nhung-nguoi-ban-ma-phan-3",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260927/nhung-nguoi-ban-ma-phan-3-poster.webp",
        "year": "2024",
        "rating": "4.0",
        "views": 83467,
        "likes": 27675,
        "comments_count": 165,
        "caption": "Review chi tiết siêu phẩm Những Người Bạn Ma (Phần 3) (Ghosts (Season 3)).",
        "categories": [
            "Hài Hước",
            "Khoa Học",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_co_nang_mot_sach_Wo28IopG2WE",
        "yt": "Wo28IopG2WE",
        "title": "Cô Nàng Mọt Sách",
        "origin_title": "Ascendance Of A Bookworm (Adopted Daughter Of An Archduke)",
        "slug": "co-nang-mot-sach",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260413-1/7a0e4154b3a97790815b0ffa25ffcf2b.jpg",
        "year": "2026",
        "rating": "4.0",
        "views": 86342,
        "likes": 26869,
        "comments_count": 193,
        "caption": "Review chi tiết siêu phẩm Cô Nàng Mọt Sách (Ascendance Of A Bookworm (Adopted Daughter Of An Archduke)).",
        "categories": [
            "Chính Kịch",
            "Khoa Học",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_gelboys_phan_2_ysnG5TFepOA",
        "yt": "ysnG5TFepOA",
        "title": "GELBOYS (Phần 2)",
        "origin_title": "GELBOYS (Season 2)",
        "slug": "gelboys-phan-2",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260809/gelboys-phan-2-poster.webp",
        "year": "2025",
        "rating": "4.1",
        "views": 94161,
        "likes": 19635,
        "comments_count": 393,
        "caption": "Review chi tiết siêu phẩm GELBOYS (Phần 2) (GELBOYS (Season 2)).",
        "categories": [
            "Chính Kịch",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_ky_tuc_xa_lam_chieu_cGfnXZBYkZQ",
        "yt": "cGfnXZBYkZQ",
        "title": "Ký Túc Xá \"Lắm Chiêu\"",
        "origin_title": "The D Dorm",
        "slug": "ky-tuc-xa-lam-chieu",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260921/ky-tuc-xa-lam-chieu-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 25243,
        "likes": 18655,
        "comments_count": 65,
        "caption": "Review chi tiết siêu phẩm Ký Túc Xá \"Lắm Chiêu\" (The D Dorm).",
        "categories": [
            "Hài Hước",
            "Chính Kịch"
        ]
    },
    {
        "id": "rev_me_ke_chi_ke_khong_he_khat_khe_gqJXnwB1qBc",
        "yt": "gqJXnwB1qBc",
        "title": "Mẹ Kế, Chị Kế Không Hề Khắt Khe",
        "origin_title": "My Stepmother And Stepsisters Aren't Wicked",
        "slug": "me-ke-chi-ke-khong-he-khat-khe",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260709/me-ke-chi-ke-khong-he-khat-khe-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 20631,
        "likes": 16732,
        "comments_count": 309,
        "caption": "Review chi tiết siêu phẩm Mẹ Kế, Chị Kế Không Hề Khắt Khe (My Stepmother And Stepsisters Aren't Wicked).",
        "categories": [
            "Hoạt Hình",
            "Hài Hước",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_dien_tinh_2026_qzwvncmhcY4",
        "yt": "qzwvncmhcY4",
        "title": "Điên Tình",
        "origin_title": "You Maniac",
        "slug": "dien-tinh-2026",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260830/dien-tinh-2026-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 21203,
        "likes": 37466,
        "comments_count": 126,
        "caption": "Review chi tiết siêu phẩm Điên Tình (You Maniac).",
        "categories": [
            "Chính Kịch",
            "Tình Cảm"
        ]
    },
    {
        "id": "rev_bon_ban_tay_hai_ban_sonata_KapADxhCvvM",
        "yt": "KapADxhCvvM",
        "title": "Bốn Bàn Tay, Hai Bản Sonata",
        "origin_title": "Four Hands, Two Sonatas",
        "slug": "bon-ban-tay-hai-ban-sonata",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260829/bon-ban-tay-hai-ban-sonata-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 70157,
        "likes": 50333,
        "comments_count": 214,
        "caption": "Review chi tiết siêu phẩm Bốn Bàn Tay, Hai Bản Sonata (Four Hands, Two Sonatas).",
        "categories": [
            "Chính Kịch",
            "Tình Cảm"
        ]
    },
    {
        "id": "rev_dau_pha_thuong_khung_phan_5_SLHuLkyHGXE",
        "yt": "SLHuLkyHGXE",
        "title": "Đấu Phá Thương Khung (Phần 5)",
        "origin_title": "Fights Break Sphere (Season 5)",
        "slug": "dau-pha-thuong-khung-phan-5",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20240822-1/58a4a1135f235b376641c5171d410b04.jpg",
        "year": "2022",
        "rating": "4.9",
        "views": 59685,
        "likes": 15275,
        "comments_count": 279,
        "caption": "Review chi tiết siêu phẩm Đấu Phá Thương Khung (Phần 5) (Fights Break Sphere (Season 5)).",
        "categories": [
            "Phiêu Lưu",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_chien_binh_anh_sang_teo_uJMDy1xHVs4",
        "yt": "uJMDy1xHVs4",
        "title": "Chiến Binh Ánh Sáng TEO",
        "origin_title": "Ultraman Teo",
        "slug": "chien-binh-anh-sang-teo",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260708/chien-binh-anh-sang-teo-poster.webp",
        "year": "2026",
        "rating": "5.0",
        "views": 40909,
        "likes": 37474,
        "comments_count": 63,
        "caption": "Review chi tiết siêu phẩm Chiến Binh Ánh Sáng TEO (Ultraman Teo).",
        "categories": [
            "Hành Động",
            "Khoa Học",
            "Phiêu Lưu",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_nhat_ky_tim_chong_cua_do_lap_lap_SkLzd9aSlNM",
        "yt": "SkLzd9aSlNM",
        "title": "Nhật Ký Tìm Chồng Của Đỗ Lạp Lạp",
        "origin_title": "Go Lala Go! 2",
        "slug": "nhat-ky-tim-chong-cua-do-lap-lap",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260926/nhat-ky-tim-chong-cua-do-lap-lap-poster.webp",
        "year": "2015",
        "rating": "2.9",
        "views": 47994,
        "likes": 25963,
        "comments_count": 178,
        "caption": "Review chi tiết siêu phẩm Nhật Ký Tìm Chồng Của Đỗ Lạp Lạp (Go Lala Go! 2).",
        "categories": [
            "Hài Hước",
            "Tình Cảm",
            "Tâm Lý",
            "Chính Kịch"
        ]
    },
    {
        "id": "rev_tan_thuoc_msF5XevzSdQ",
        "yt": "msF5XevzSdQ",
        "title": "Tàn Thuốc",
        "origin_title": "Ash",
        "slug": "tan-thuoc",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260817/tan-thuoc-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 36515,
        "likes": 8303,
        "comments_count": 87,
        "caption": "Review chi tiết siêu phẩm Tàn Thuốc (Ash).",
        "categories": [
            "Chính Kịch",
            "Hình Sự",
            "Hành Động",
            "Phiêu Lưu",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_pham_nhan_tu_tien_WSzxfY5OHG0",
        "yt": "WSzxfY5OHG0",
        "title": "Phàm Nhân Tu Tiên",
        "origin_title": "A Record of a Mortal's Journey to Immortality",
        "slug": "pham-nhan-tu-tien",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20240715-1/ed827a6e5d8f7c41aa0728403665cd87.jpg",
        "year": "2020",
        "rating": "4.2",
        "views": 44187,
        "likes": 48365,
        "comments_count": 315,
        "caption": "Review chi tiết siêu phẩm Phàm Nhân Tu Tiên (A Record of a Mortal's Journey to Immortality).",
        "categories": [
            "Hành Động",
            "Phiêu Lưu",
            "Thần Thoại",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_ham_silo_phan_1_8ZYhuvIv1pA",
        "yt": "8ZYhuvIv1pA",
        "title": "Hầm SILO (Phần 1)",
        "origin_title": "Silo (Season 1)",
        "slug": "ham-silo-phan-1",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260704-1/52845d44789dddbdfbd6bb5142668c6d.jpg",
        "year": "2023",
        "rating": "4.1",
        "views": 47940,
        "likes": 42216,
        "comments_count": 61,
        "caption": "Review chi tiết siêu phẩm Hầm SILO (Phần 1) (Silo (Season 1)).",
        "categories": [
            "Khoa Học",
            "Viễn Tưởng",
            "Chính Kịch",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_thieu_chu_gioi_chay_tron_phan_2_I6A5NHaXvvk",
        "yt": "I6A5NHaXvvk",
        "title": "Thiếu Chủ Giỏi Chạy Trốn (Phần 2)",
        "origin_title": "The Elusive Samurai (Season 2)",
        "slug": "thieu-chu-gioi-chay-tron-phan-2",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260719/thieu-chu-gioi-chay-tron-phan-2-poster.webp",
        "year": "2026",
        "rating": "3.9",
        "views": 92535,
        "likes": 13412,
        "comments_count": 156,
        "caption": "Review chi tiết siêu phẩm Thiếu Chủ Giỏi Chạy Trốn (Phần 2) (The Elusive Samurai (Season 2)).",
        "categories": [
            "Hoạt Hình",
            "Hành Động",
            "Phiêu Lưu",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_sinagtala_c1ZG2cfkulw",
        "yt": "c1ZG2cfkulw",
        "title": "Sinagtala",
        "origin_title": "Sinagtala",
        "slug": "sinagtala",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260926/sinagtala-poster.webp",
        "year": "2025",
        "rating": "4.9",
        "views": 52027,
        "likes": 19921,
        "comments_count": 99,
        "caption": "Review chi tiết siêu phẩm Sinagtala (Sinagtala).",
        "categories": [
            "Chính Kịch",
            "Gia Đình"
        ]
    },
    {
        "id": "rev_di_san_vay_mau_phan_2_0-TBHiOReng",
        "yt": "0-TBHiOReng",
        "title": "Di sản vấy máu (Phần 2)",
        "origin_title": "Blood Legacy (Season 2)",
        "slug": "di-san-vay-mau-phan-2",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260926/di-san-vay-mau-phan-2-poster.webp",
        "year": "2026",
        "rating": "3.6",
        "views": 45227,
        "likes": 10367,
        "comments_count": 202,
        "caption": "Review chi tiết siêu phẩm Di sản vấy máu (Phần 2) (Blood Legacy (Season 2)).",
        "categories": [
            "Chính Kịch"
        ]
    },
    {
        "id": "rev_ve_xong_di_roi_hay_chet_jI61NtGuxV4",
        "yt": "jI61NtGuxV4",
        "title": "Vẽ Xong Đi, Rồi Hãy Chết!",
        "origin_title": "Draw This, Then Die!",
        "slug": "ve-xong-di-roi-hay-chet",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260705-1/6b0abe9e476c2371ef7e79a385f58479.jpg",
        "year": "2026",
        "rating": "4.0",
        "views": 47025,
        "likes": 44893,
        "comments_count": 290,
        "caption": "Review chi tiết siêu phẩm Vẽ Xong Đi, Rồi Hãy Chết! (Draw This, Then Die!).",
        "categories": [
            "Chính Kịch",
            "Hài Hước",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_lang_nghe_thanh_am_PRX0vwUvURg",
        "yt": "PRX0vwUvURg",
        "title": "Lắng Nghe Thanh Âm",
        "origin_title": "Oops! Mysterious Sounds",
        "slug": "lang-nghe-thanh-am",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260919/lang-nghe-thanh-am-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 39635,
        "likes": 26785,
        "comments_count": 132,
        "caption": "Review chi tiết siêu phẩm Lắng Nghe Thanh Âm (Oops! Mysterious Sounds).",
        "categories": [
            "Chính Kịch",
            "Khoa Học",
            "Viễn Tưởng",
            "Bí Ẩn"
        ]
    },
    {
        "id": "rev_luc_do_toi_da_chuyen_sinh_thanh_slime_phan_4_RUP2Jj7v0BE",
        "yt": "RUP2Jj7v0BE",
        "title": "Lúc Đó Tôi Đã Chuyển Sinh Thành Slime (Phần 4)",
        "origin_title": "That Time I Got Reincarnated As A Slime (Season 4)",
        "slug": "luc-do-toi-da-chuyen-sinh-thanh-slime-phan-4",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260407-1/ab90a78161fa03e2b3f48f84bf250d05.jpg",
        "year": "2026",
        "rating": "4.2",
        "views": 22543,
        "likes": 52358,
        "comments_count": 304,
        "caption": "Review chi tiết siêu phẩm Lúc Đó Tôi Đã Chuyển Sinh Thành Slime (Phần 4) (That Time I Got Reincarnated As A Slime (Season 4)).",
        "categories": [
            "Hài Hước",
            "Hành Động",
            "Khoa Học",
            "Phiêu Lưu",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_yeu_duoc_khong_N6bdFaf37Ms",
        "yt": "N6bdFaf37Ms",
        "title": "Yêu Được Không",
        "origin_title": "Pls Love",
        "slug": "yeu-duoc-khong",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260914/yeu-duoc-khong-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 56072,
        "likes": 31456,
        "comments_count": 293,
        "caption": "Review chi tiết siêu phẩm Yêu Được Không (Pls Love).",
        "categories": [
            "Chính Kịch",
            "Tình Cảm"
        ]
    },
    {
        "id": "rev_cuoc_phieu_luu_ki_la_cua_jojo_phan_6_b51C8AbRDGU",
        "yt": "b51C8AbRDGU",
        "title": "Cuộc Phiêu Lưu Kì Lạ Của JoJo (Phần 6)",
        "origin_title": "JoJo's Bizarre Adventure (Season 6) (Steel Ball Run)",
        "slug": "cuoc-phieu-luu-ki-la-cua-jojo-phan-6",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260222-1/a258273d30b04ac810a90432688e7239.jpg",
        "year": "2026",
        "rating": "4.3",
        "views": 30759,
        "likes": 12613,
        "comments_count": 38,
        "caption": "Review chi tiết siêu phẩm Cuộc Phiêu Lưu Kì Lạ Của JoJo (Phần 6) (JoJo's Bizarre Adventure (Season 6) (Steel Ball Run)).",
        "categories": [
            "Hành Động",
            "Phiêu Lưu",
            "Khoa Học",
            "Viễn Tưởng",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_lanh_dia_tu_chien_phan_2_qKGgw7Ob5f4",
        "yt": "qKGgw7Ob5f4",
        "title": "Lãnh Địa Tử Chiến (Phần 2)",
        "origin_title": "MobLand (Season 2)",
        "slug": "lanh-dia-tu-chien-phan-2",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260921/lanh-dia-tu-chien-phan-2-poster.webp",
        "year": "2026",
        "rating": "4.2",
        "views": 28433,
        "likes": 24136,
        "comments_count": 302,
        "caption": "Review chi tiết siêu phẩm Lãnh Địa Tử Chiến (Phần 2) (MobLand (Season 2)).",
        "categories": [
            "Hình Sự",
            "Chính Kịch"
        ]
    },
    {
        "id": "rev_nhung_diep_vien_het_thoi_phan_6_O9ZJChzPn0U",
        "yt": "O9ZJChzPn0U",
        "title": "Những Điệp Viên Hết Thời (Phần 6)",
        "origin_title": "Slow Horses (Season 6)",
        "slug": "nhung-diep-vien-het-thoi-phan-6",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260925/nhung-diep-vien-het-thoi-phan-6-poster.webp",
        "year": "2026",
        "rating": "4.0",
        "views": 47428,
        "likes": 26136,
        "comments_count": 399,
        "caption": "Review chi tiết siêu phẩm Những Điệp Viên Hết Thời (Phần 6) (Slow Horses (Season 6)).",
        "categories": [
            "Hình Sự",
            "Chính Kịch",
            "Bí Ẩn"
        ]
    },
    {
        "id": "rev_loi_thu_nhan_bi_mat_25_nam_r8650GeeL78",
        "yt": "r8650GeeL78",
        "title": "Lời Thú Nhận: Bí Mật 25 Năm",
        "origin_title": "25 Years Of You",
        "slug": "loi-thu-nhan-bi-mat-25-nam",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260717/loi-thu-nhan-bi-mat-25-nam-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 36865,
        "likes": 43723,
        "comments_count": 154,
        "caption": "Review chi tiết siêu phẩm Lời Thú Nhận: Bí Mật 25 Năm (25 Years Of You).",
        "categories": [
            "Chính Kịch",
            "Tâm Lý",
            "Tình Cảm"
        ]
    },
    {
        "id": "rev_dau_la_dai_luc_2_tuyet_the_duong_mon_w2nRoKFcFuo",
        "yt": "w2nRoKFcFuo",
        "title": "Đấu La Đại Lục 2 (Tuyệt Thế Đường Môn)",
        "origin_title": "Soul Land 2 (The Peerless Tang Clan)",
        "slug": "dau-la-dai-luc-2-tuyet-the-duong-mon",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20240103-1/af2ae10bcb72617994f00dce440205dc.jpg",
        "year": "2023",
        "rating": "4.0",
        "views": 22989,
        "likes": 28606,
        "comments_count": 235,
        "caption": "Review chi tiết siêu phẩm Đấu La Đại Lục 2 (Tuyệt Thế Đường Môn) (Soul Land 2 (The Peerless Tang Clan)).",
        "categories": [
            "Hành Động",
            "Phiêu Lưu",
            "Võ Thuật"
        ]
    },
    {
        "id": "rev_vu_an_cuoi_cung_phan_1_yLeja7kWgmU",
        "yt": "yLeja7kWgmU",
        "title": "Vụ án cuối cùng (Phần 1)",
        "origin_title": "The Final Problem (Season 1)",
        "slug": "vu-an-cuoi-cung-phan-1",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260925/vu-an-cuoi-cung-phan-1-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 32751,
        "likes": 32339,
        "comments_count": 310,
        "caption": "Review chi tiết siêu phẩm Vụ án cuối cùng (Phần 1) (The Final Problem (Season 1)).",
        "categories": [
            "Hình Sự",
            "Bí Ẩn"
        ]
    },
    {
        "id": "rev_unabomber_B3tR6qQjbgI",
        "yt": "B3tR6qQjbgI",
        "title": "UNABOMBER",
        "origin_title": "UNABOMBER",
        "slug": "unabomber",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260925/unabomber-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 24253,
        "likes": 23902,
        "comments_count": 190,
        "caption": "Review chi tiết siêu phẩm UNABOMBER (UNABOMBER).",
        "categories": [
            "Tâm Lý",
            "Hình Sự",
            "Lịch Sử"
        ]
    },
    {
        "id": "rev_mot_the_gioi_khac_biet_phan_1_W8jMEXwErvk",
        "yt": "W8jMEXwErvk",
        "title": "Một thế giới khác biệt (Phần 1)",
        "origin_title": "A Different World (Season 1)",
        "slug": "mot-the-gioi-khac-biet-phan-1",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260925/mot-the-gioi-khac-biet-phan-1-poster.webp",
        "year": "2026",
        "rating": "2.6",
        "views": 66847,
        "likes": 36493,
        "comments_count": 83,
        "caption": "Review chi tiết siêu phẩm Một thế giới khác biệt (Phần 1) (A Different World (Season 1)).",
        "categories": [
            "Hài Hước",
            "Chính Kịch"
        ]
    },
    {
        "id": "rev_nguoi_mang_mat_na_sat_gnNt7l2nA_o",
        "yt": "gnNt7l2nA_o",
        "title": "Người Mang Mặt Nạ Sắt",
        "origin_title": "The Man In The Iron Mask",
        "slug": "nguoi-mang-mat-na-sat",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260925/nguoi-mang-mat-na-sat-poster.webp",
        "year": "1998",
        "rating": "3.4",
        "views": 44132,
        "likes": 47666,
        "comments_count": 88,
        "caption": "Review chi tiết siêu phẩm Người Mang Mặt Nạ Sắt (The Man In The Iron Mask).",
        "categories": [
            "Phiêu Lưu",
            "Hành Động",
            "Chính Kịch",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_co_meo_nghien_thuoc_la_KYGgyQtSAdI",
        "yt": "KYGgyQtSAdI",
        "title": "Cô Mèo Nghiện Thuốc Lá",
        "origin_title": "Chainsmoker Cat",
        "slug": "co-meo-nghien-thuoc-la",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260704-1/81bc916a371d97829898f3fac118381e.jpg",
        "year": "2026",
        "rating": "3.8",
        "views": 26432,
        "likes": 28954,
        "comments_count": 241,
        "caption": "Review chi tiết siêu phẩm Cô Mèo Nghiện Thuốc Lá (Chainsmoker Cat).",
        "categories": [
            "Hài Hước",
            "Khoa Học",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_nguoi_chay_xuyen_khong_gian_phan_2_j6ucGt_Xp14",
        "yt": "j6ucGt_Xp14",
        "title": "Người Chạy Xuyên Không Gian (Phần 2)",
        "origin_title": "Dark Matter (Season 2)",
        "slug": "nguoi-chay-xuyen-khong-gian-phan-2",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260829/nguoi-chay-xuyen-khong-gian-phan-2-poster.webp",
        "year": "2026",
        "rating": "3.9",
        "views": 66573,
        "likes": 13235,
        "comments_count": 167,
        "caption": "Review chi tiết siêu phẩm Người Chạy Xuyên Không Gian (Phần 2) (Dark Matter (Season 2)).",
        "categories": [
            "Khoa Học",
            "Viễn Tưởng",
            "Chính Kịch"
        ]
    },
    {
        "id": "rev_stuart_cuu_khong_noi_vu_tru_phan_1__blrWb1yZiY",
        "yt": "_blrWb1yZiY",
        "title": "Stuart Cứu Không Nổi Vũ Trụ (Phần 1)",
        "origin_title": "Stuart Fails to Save the Universe (Season 1)",
        "slug": "stuart-cuu-khong-noi-vu-tru-phan-1",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260817/stuart-cuu-khong-noi-vu-tru-phan-1-poster.webp",
        "year": "2026",
        "rating": "4.5",
        "views": 48802,
        "likes": 34538,
        "comments_count": 221,
        "caption": "Review chi tiết siêu phẩm Stuart Cứu Không Nổi Vũ Trụ (Phần 1) (Stuart Fails to Save the Universe (Season 1)).",
        "categories": [
            "Hài Hước",
            "Khoa Học",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_son_hai_kinh_thiet_lap_lai_trat_tu_H8X1y7sxXGo",
        "yt": "H8X1y7sxXGo",
        "title": "Sơn Hải Kinh: Thiết Lập Lại Trật Tự",
        "origin_title": "Threads of Fate: A War Untold / The Classic of Mountains and Seas: Return to Order",
        "slug": "son-hai-kinh-thiet-lap-lai-trat-tu",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260719/son-hai-kinh-thiet-lap-lai-trat-tu-poster.webp",
        "year": "2026",
        "rating": "3.5",
        "views": 39221,
        "likes": 45003,
        "comments_count": 47,
        "caption": "Review chi tiết siêu phẩm Sơn Hải Kinh: Thiết Lập Lại Trật Tự (Threads of Fate: A War Untold / The Classic of Mountains and Seas: Return to Order).",
        "categories": [
            "Hoạt Hình",
            "Khoa Học",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_thuong_nguyen_do_fB0tAzBO4aY",
        "yt": "fB0tAzBO4aY",
        "title": "Thương Nguyên Đồ",
        "origin_title": "The Demon Hunter",
        "slug": "thuong-nguyen-do",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20250530-1/435941e1bbd5462ab142b2d1d03b608e.jpg",
        "year": "2023",
        "rating": "4.6",
        "views": 59703,
        "likes": 9436,
        "comments_count": 313,
        "caption": "Review chi tiết siêu phẩm Thương Nguyên Đồ (The Demon Hunter).",
        "categories": [
            "Chính Kịch",
            "Hành Động",
            "Phiêu Lưu",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_chuyen_canh_xuyen_khong_EG_1b0JjPso",
        "yt": "EG_1b0JjPso",
        "title": "Chuyển Cảnh! Xuyên Không",
        "origin_title": "Slate",
        "slug": "chuyen-canh-xuyen-khong",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260925/chuyen-canh-xuyen-khong-poster.webp",
        "year": "2020",
        "rating": "3.1",
        "views": 39236,
        "likes": 23666,
        "comments_count": 196,
        "caption": "Review chi tiết siêu phẩm Chuyển Cảnh! Xuyên Không (Slate).",
        "categories": [
            "Hành Động",
            "Hài Hước",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_yeu_nhau_den_tan_ngay_cau_bien_mat_B4fw52Jueyk",
        "yt": "B4fw52Jueyk",
        "title": "Yêu Nhau Đến Tận Ngày Cậu Biến Mất",
        "origin_title": "I Want To Love You Till Your Dying Day",
        "slug": "yeu-nhau-den-tan-ngay-cau-bien-mat",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260708/yeu-nhau-den-tan-ngay-cau-bien-mat-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 32578,
        "likes": 18727,
        "comments_count": 262,
        "caption": "Review chi tiết siêu phẩm Yêu Nhau Đến Tận Ngày Cậu Biến Mất (I Want To Love You Till Your Dying Day).",
        "categories": [
            "Chính Kịch",
            "Hoạt Hình",
            "Khoa Học",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_trong_giap_hiep_si_chuyen_sinh_bi_luu_day_tro_nen_vo_dich_nho_kien_thuc_ve_game_OnSv9T8PWwI",
        "yt": "OnSv9T8PWwI",
        "title": "Trọng Giáp Hiệp Sĩ Chuyển Sinh Bị Lưu Đày Trở Nên Vô Địch Nhờ Kiến Thức Về Game",
        "origin_title": "The Exiled Heavy Knight Knows How To Game The System",
        "slug": "trong-giap-hiep-si-chuyen-sinh-bi-luu-day-tro-nen-vo-dich-nho-kien-thuc-ve-game",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260704-1/4b4d7d08fc0707be4fe3940998383a8f.jpg",
        "year": "2026",
        "rating": "4.0",
        "views": 42736,
        "likes": 28226,
        "comments_count": 156,
        "caption": "Review chi tiết siêu phẩm Trọng Giáp Hiệp Sĩ Chuyển Sinh Bị Lưu Đày Trở Nên Vô Địch Nhờ Kiến Thức Về Game (The Exiled Heavy Knight Knows How To Game The System).",
        "categories": [
            "Hành Động",
            "Khoa Học",
            "Phiêu Lưu",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_dac_vu_xanh_phan_1_lh6elskHp8Q",
        "yt": "lh6elskHp8Q",
        "title": "Đặc vụ xanh (Phần 1)",
        "origin_title": "Blue Season (Season 1)",
        "slug": "dac-vu-xanh-phan-1",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260925/dac-vu-xanh-phan-1-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 63697,
        "likes": 27942,
        "comments_count": 145,
        "caption": "Review chi tiết siêu phẩm Đặc vụ xanh (Phần 1) (Blue Season (Season 1)).",
        "categories": [
            "Hình Sự",
            "Tâm Lý",
            "Hành Động"
        ]
    },
    {
        "id": "rev_bui_mebius_ByOF3FLlAws",
        "yt": "ByOF3FLlAws",
        "title": "Bụi Mebius",
        "origin_title": "MEBIUS DUST",
        "slug": "bui-mebius",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260710/bui-mebius-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 42724,
        "likes": 29672,
        "comments_count": 65,
        "caption": "Review chi tiết siêu phẩm Bụi Mebius (MEBIUS DUST).",
        "categories": [
            "Hoạt Hình",
            "Hành Động",
            "Khoa Học",
            "Phiêu Lưu",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_dai_chua_te_3d_hQTb1OwOeJg",
        "yt": "hQTb1OwOeJg",
        "title": "Đại Chúa Tể 3D",
        "origin_title": "The Great Ruler",
        "slug": "dai-chua-te-3d",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260415-1/b5d7394aa49cde793f86f5d9163ced85.jpg",
        "year": "2023",
        "rating": "4.5",
        "views": 33511,
        "likes": 44483,
        "comments_count": 121,
        "caption": "Review chi tiết siêu phẩm Đại Chúa Tể 3D (The Great Ruler).",
        "categories": [
            "Hành Động",
            "Khoa Học",
            "Phiêu Lưu",
            "Tâm Lý",
            "Viễn Tưởng"
        ]
    },
    {
        "id": "rev_vuot_nguc_phan_5_AL9zLctDJaU",
        "yt": "AL9zLctDJaU",
        "title": "Vượt Ngục (Phần 5)",
        "origin_title": "Prison Break (Season 5): Sequel",
        "slug": "vuot-nguc-phan-5",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20240409-1/d2f1e11648689897162e2cc874265c82.jpg",
        "year": "2017",
        "rating": "4.0",
        "views": 93311,
        "likes": 20815,
        "comments_count": 261,
        "caption": "Review chi tiết siêu phẩm Vượt Ngục (Phần 5) (Prison Break (Season 5): Sequel).",
        "categories": [
            "Hành Động",
            "Hình Sự"
        ]
    },
    {
        "id": "rev_truy_tim_cong_ly_BOzNaa_o9_g",
        "yt": "BOzNaa_o9_g",
        "title": "Truy Tìm Công Lý",
        "origin_title": "Neagley",
        "slug": "truy-tim-cong-ly",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260920/truy-tim-cong-ly-poster.webp",
        "year": "2026",
        "rating": "4.0",
        "views": 51693,
        "likes": 49266,
        "comments_count": 265,
        "caption": "Review chi tiết siêu phẩm Truy Tìm Công Lý (Neagley).",
        "categories": [
            "Chính Kịch",
            "Bí Ẩn",
            "Hình Sự"
        ]
    },
    {
        "id": "rev_u_thi_ly_hon_nMfSOQJ4kOM",
        "yt": "nMfSOQJ4kOM",
        "title": "Ừ Thì Ly Hôn!",
        "origin_title": "OK! Let's Get Divorced",
        "slug": "u-thi-ly-hon",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260821/u-thi-ly-hon-poster.webp",
        "year": "2026",
        "rating": "4.9",
        "views": 78279,
        "likes": 25344,
        "comments_count": 211,
        "caption": "Review chi tiết siêu phẩm Ừ Thì Ly Hôn! (OK! Let's Get Divorced).",
        "categories": [
            "Chính Kịch",
            "Hài Hước",
            "Gia Đình",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_hut_thuoc_phia_sau_sieu_thi_cung_em_hien_sau_sieu_thi_muon_phien_bay_di_kynbQYIVK7I",
        "yt": "kynbQYIVK7I",
        "title": "Hút Thuốc Phía Sau Siêu Thị Cùng Em (Hiên Sau Siêu Thị, Muộn Phiền Bay Đi)",
        "origin_title": "Smoking Behind The Supermarket With You",
        "slug": "hut-thuoc-phia-sau-sieu-thi-cung-em-hien-sau-sieu-thi-muon-phien-bay-di",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260711/hut-thuoc-phia-sau-sieu-thi-cung-em-hien-sau-sieu-thi-muon-phien-bay-di-poster.webp",
        "year": "2026",
        "rating": "4.7",
        "views": 38166,
        "likes": 43513,
        "comments_count": 309,
        "caption": "Review chi tiết siêu phẩm Hút Thuốc Phía Sau Siêu Thị Cùng Em (Hiên Sau Siêu Thị, Muộn Phiền Bay Đi) (Smoking Behind The Supermarket With You).",
        "categories": [
            "Chính Kịch",
            "Hoạt Hình",
            "Hài Hước",
            "Tâm Lý"
        ]
    },
    {
        "id": "rev_ngay_he_zY9mTImaoBg",
        "yt": "zY9mTImaoBg",
        "title": "Ngày Hè",
        "origin_title": "Summertime",
        "slug": "ngay-he",
        "type": "review",
        "poster": "https://phimimg.com/uploads/movies/20260828/ngay-he-poster.webp",
        "year": "2026",
        "rating": "3.5",
        "views": 55518,
        "likes": 14373,
        "comments_count": 370,
        "caption": "Review chi tiết siêu phẩm Ngày Hè (Summertime).",
        "categories": [
            "Chính Kịch",
            "Tình Cảm"
        ]
    },
    {
        "id": "rev_cuoc_song_o_thoi_lenh_hoa_cua_ngai_dara_c5a6kc3ZGnk",
        "yt": "c5a6kc3ZGnk",
        "title": "Cuộc Sống Ở Thời Lệnh Hòa Của Ngài Dara",
        "origin_title": "Dara-san Of Reiwa",
        "slug": "cuoc-song-o-thoi-lenh-hoa-cua-ngai-dara",
        "type": "review",
        "poster": "https://phimimg.com/upload/vod/20260703-1/fa2d431e68ed9e55d3d455b57253d1d7.jpg",
        "year": "2026",
        "rating": "4.0",
        "views": 43603,
        "likes": 33359,
        "comments_count": 134,
        "caption": "Review chi tiết siêu phẩm Cuộc Sống Ở Thời Lệnh Hòa Của Ngài Dara (Dara-san Of Reiwa).",
        "categories": [
            "Chính Kịch",
            "Hài Hước",
            "Tâm Lý"
        ]
    }
],
    CURATED_REELS: [
    {
        "id": "reel_v_qLptbTLNJGo",
        "yt": "qLptbTLNJGo",
        "title": "Những Câu Nói Hay Của Châu Tinh Trì   #tamtrang",
        "origin_title": "Những Câu Nói Hay Của Châu Tinh Trì   #tamtrang",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Em gái vùng cao",
        "poster": "https://i.ytimg.com/vi/qLptbTLNJGo/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 301500,
        "likes": 75541,
        "comments_count": 1281,
        "caption": "Những Câu Nói Hay Của Châu Tinh Trì   #tamtrang - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_s_NWSnhHNxg",
        "yt": "s_NWSnhHNxg",
        "title": "Đôi mắt tràn đầy ham muốn 😍#vungtromkhongthegiau #hiddenlove #trieulotu #trantrietvien",
        "origin_title": "Đôi mắt tràn đầy ham muốn 😍#vungtromkhongthegiau #hiddenlove #trieulotu #trantrietvien",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "YOUKU Vietnam-Tải APP Ngay",
        "poster": "https://i.ytimg.com/vi/s_NWSnhHNxg/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 839456,
        "likes": 57472,
        "comments_count": 1074,
        "caption": "Đôi mắt tràn đầy ham muốn 😍#vungtromkhongthegiau #hiddenlove #trieulotu #trantrietvien - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_Bizwkb33XSs",
        "yt": "Bizwkb33XSs",
        "title": "💕 Cặp Đôi Chính Cùng Thả Tim, Ngọt Ngào Hết Nấc! 🫶😍 #NhấtÂuXuân #iQIYI",
        "origin_title": "💕 Cặp Đôi Chính Cùng Thả Tim, Ngọt Ngào Hết Nấc! 🫶😍 #NhấtÂuXuân #iQIYI",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "iQIYI Phim Thuyết Minh - Get the iQIYI APP",
        "poster": "https://i.ytimg.com/vi/Bizwkb33XSs/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 445314,
        "likes": 70339,
        "comments_count": 160,
        "caption": "💕 Cặp Đôi Chính Cùng Thả Tim, Ngọt Ngào Hết Nấc! 🫶😍 #NhấtÂuXuân #iQIYI - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_PBmIU0fDQGo",
        "yt": "PBmIU0fDQGo",
        "title": "🕺 Trần Triết Viễn Nhảy Điệu Tay Cực Cuốn, Đáng Yêu Đốn Tim Fan! 😍💕 #NhấtTiếuTùyCa #iQIYI",
        "origin_title": "🕺 Trần Triết Viễn Nhảy Điệu Tay Cực Cuốn, Đáng Yêu Đốn Tim Fan! 😍💕 #NhấtTiếuTùyCa #iQIYI",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "iQIYI Phim Thuyết Minh - Get the iQIYI APP",
        "poster": "https://i.ytimg.com/vi/PBmIU0fDQGo/hqdefault.jpg",
        "year": "2026",
        "rating": "5.0",
        "views": 52063,
        "likes": 55668,
        "comments_count": 978,
        "caption": "🕺 Trần Triết Viễn Nhảy Điệu Tay Cực Cuốn, Đáng Yêu Đốn Tim Fan! 😍💕 #NhấtTiếuTùyCa #iQIYI - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_GRU4QkCf4pg",
        "yt": "GRU4QkCf4pg",
        "title": "hay 🥰🥰🥰#VụngTrộmKhôngThểGiấu  #hiddenlove #TriệuLộTư  #TrầnTriếtViễn #zhaolusi #chenzheyuan",
        "origin_title": "hay 🥰🥰🥰#VụngTrộmKhôngThểGiấu  #hiddenlove #TriệuLộTư  #TrầnTriếtViễn #zhaolusi #chenzheyuan",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "YOUKU Vietnam-Tải APP Ngay",
        "poster": "https://i.ytimg.com/vi/GRU4QkCf4pg/hqdefault.jpg",
        "year": "2026",
        "rating": "4.6",
        "views": 56710,
        "likes": 45703,
        "comments_count": 892,
        "caption": "hay 🥰🥰🥰#VụngTrộmKhôngThểGiấu  #hiddenlove #TriệuLộTư  #TrầnTriếtViễn #zhaolusi #chenzheyuan - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_BDOym5CQ-cw",
        "yt": "BDOym5CQ-cw",
        "title": "trích đoạn từ phim ai ngắn",
        "origin_title": "trích đoạn từ phim ai ngắn",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Huyễn Cảnh AI Cinema",
        "poster": "https://i.ytimg.com/vi/BDOym5CQ-cw/hqdefault.jpg",
        "year": "2026",
        "rating": "4.6",
        "views": 133355,
        "likes": 63497,
        "comments_count": 1309,
        "caption": "trích đoạn từ phim ai ngắn - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_jH8-XYemGcg",
        "yt": "jH8-XYemGcg",
        "title": "Ghen Tuông Mù Quáng - Phim Việt Nam Hay",
        "origin_title": "Ghen Tuông Mù Quáng - Phim Việt Nam Hay",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Viet Film",
        "poster": "https://i.ytimg.com/vi/jH8-XYemGcg/hqdefault.jpg",
        "year": "2026",
        "rating": "4.9",
        "views": 221584,
        "likes": 22724,
        "comments_count": 1290,
        "caption": "Ghen Tuông Mù Quáng - Phim Việt Nam Hay - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_Pv90DZSpKNQ",
        "yt": "Pv90DZSpKNQ",
        "title": "Trích đoạn phim",
        "origin_title": "Trích đoạn phim",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Thế Giới Loài Thú",
        "poster": "https://i.ytimg.com/vi/Pv90DZSpKNQ/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 831174,
        "likes": 80338,
        "comments_count": 440,
        "caption": "Trích đoạn phim - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_GEHxu9BzxUQ",
        "yt": "GEHxu9BzxUQ",
        "title": "Đại tiểu thư bị vạch trần mưu kế  phim ngôn tình hay nhất",
        "origin_title": "Đại tiểu thư bị vạch trần mưu kế  phim ngôn tình hay nhất",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Clip Phim Moi",
        "poster": "https://i.ytimg.com/vi/GEHxu9BzxUQ/hqdefault.jpg",
        "year": "2026",
        "rating": "4.7",
        "views": 374869,
        "likes": 67008,
        "comments_count": 399,
        "caption": "Đại tiểu thư bị vạch trần mưu kế  phim ngôn tình hay nhất - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_Ws7hql07-rw",
        "yt": "Ws7hql07-rw",
        "title": "Đại Ca Mắt Chột Bị Giang Hồ Tập Kích  phim hành động Song Hùng",
        "origin_title": "Đại Ca Mắt Chột Bị Giang Hồ Tập Kích  phim hành động Song Hùng",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "BH Entertainment",
        "poster": "https://i.ytimg.com/vi/Ws7hql07-rw/hqdefault.jpg",
        "year": "2026",
        "rating": "5.0",
        "views": 851010,
        "likes": 104740,
        "comments_count": 359,
        "caption": "Đại Ca Mắt Chột Bị Giang Hồ Tập Kích  phim hành động Song Hùng - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_uJQ-F-gOS2s",
        "yt": "uJQ-F-gOS2s",
        "title": "Bắt Gian Tại Trận - Video Hay",
        "origin_title": "Bắt Gian Tại Trận - Video Hay",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Phim Hay Điện Ảnh Mới Nhất ",
        "poster": "https://i.ytimg.com/vi/uJQ-F-gOS2s/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 303468,
        "likes": 34561,
        "comments_count": 479,
        "caption": "Bắt Gian Tại Trận - Video Hay - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_otI0g6WPKEk",
        "yt": "otI0g6WPKEk",
        "title": "Nuôi 20 năm vẫn vứt bỏ vì không phải ruột thịt  phim ngôn tình hay nhất",
        "origin_title": "Nuôi 20 năm vẫn vứt bỏ vì không phải ruột thịt  phim ngôn tình hay nhất",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Clip Phim Moi",
        "poster": "https://i.ytimg.com/vi/otI0g6WPKEk/hqdefault.jpg",
        "year": "2026",
        "rating": "5.0",
        "views": 207075,
        "likes": 82870,
        "comments_count": 855,
        "caption": "Nuôi 20 năm vẫn vứt bỏ vì không phải ruột thịt  phim ngôn tình hay nhất - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_h5CglHQC40M",
        "yt": "h5CglHQC40M",
        "title": "Video Tú Bà Thương Người - Phim Việt Nam Hay",
        "origin_title": "Video Tú Bà Thương Người - Phim Việt Nam Hay",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Viet Film",
        "poster": "https://i.ytimg.com/vi/h5CglHQC40M/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 365385,
        "likes": 106713,
        "comments_count": 1268,
        "caption": "Video Tú Bà Thương Người - Phim Việt Nam Hay - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_TyR9tHBQHws",
        "yt": "TyR9tHBQHws",
        "title": "Trích đoạn Phim hay nhất của Hiu TV/",
        "origin_title": "Trích đoạn Phim hay nhất của Hiu TV/",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Hiu Vlog - ma síu làm nông ",
        "poster": "https://i.ytimg.com/vi/TyR9tHBQHws/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 569418,
        "likes": 86505,
        "comments_count": 837,
        "caption": "Trích đoạn Phim hay nhất của Hiu TV/ - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_0_taQ_rdP3s",
        "yt": "0_taQ_rdP3s",
        "title": "Mẹ ruột chì chiết con gái mà không hay biết  phim ngôn tình hay nhất",
        "origin_title": "Mẹ ruột chì chiết con gái mà không hay biết  phim ngôn tình hay nhất",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Clip Phim Moi",
        "poster": "https://i.ytimg.com/vi/0_taQ_rdP3s/hqdefault.jpg",
        "year": "2026",
        "rating": "4.6",
        "views": 250575,
        "likes": 43387,
        "comments_count": 1159,
        "caption": "Mẹ ruột chì chiết con gái mà không hay biết  phim ngôn tình hay nhất - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_hVTAjCA1D7E",
        "yt": "hVTAjCA1D7E",
        "title": "Chủ tịch phát hiện sự thật về con gái  phim ngôn tình hay nhất",
        "origin_title": "Chủ tịch phát hiện sự thật về con gái  phim ngôn tình hay nhất",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Clip Phim Moi",
        "poster": "https://i.ytimg.com/vi/hVTAjCA1D7E/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 208500,
        "likes": 51988,
        "comments_count": 198,
        "caption": "Chủ tịch phát hiện sự thật về con gái  phim ngôn tình hay nhất - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_i19tD6XVsjY",
        "yt": "i19tD6XVsjY",
        "title": "Cao thủ 2 tay 2 súng thủ tiêu lính nhật  phim hành động song hùng",
        "origin_title": "Cao thủ 2 tay 2 súng thủ tiêu lính nhật  phim hành động song hùng",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "BH Entertainment",
        "poster": "https://i.ytimg.com/vi/i19tD6XVsjY/hqdefault.jpg",
        "year": "2026",
        "rating": "4.6",
        "views": 132270,
        "likes": 95804,
        "comments_count": 1174,
        "caption": "Cao thủ 2 tay 2 súng thủ tiêu lính nhật  phim hành động song hùng - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_CEvH_YREMP0",
        "yt": "CEvH_YREMP0",
        "title": "Cặp đôi sát thủ tẩu thoát ngoạn mục  phim hành động song hùng",
        "origin_title": "Cặp đôi sát thủ tẩu thoát ngoạn mục  phim hành động song hùng",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "BH Entertainment",
        "poster": "https://i.ytimg.com/vi/CEvH_YREMP0/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 383769,
        "likes": 74413,
        "comments_count": 1245,
        "caption": "Cặp đôi sát thủ tẩu thoát ngoạn mục  phim hành động song hùng - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_kYLoouUdZow",
        "yt": "kYLoouUdZow",
        "title": "Cô gái bị làm nhục bởi ông chủ   #dramas",
        "origin_title": "Cô gái bị làm nhục bởi ông chủ   #dramas",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Nghiện Hoa Ngữ",
        "poster": "https://i.ytimg.com/vi/kYLoouUdZow/hqdefault.jpg",
        "year": "2026",
        "rating": "4.9",
        "views": 511530,
        "likes": 18041,
        "comments_count": 245,
        "caption": "Cô gái bị làm nhục bởi ông chủ   #dramas - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_PzM25ZtOzFo",
        "yt": "PzM25ZtOzFo",
        "title": "Tổng tài uống rượu siêu cuốn #Nửalàđườngmậtnửalàđauthương #LaVânHi #BạchLộc #iQIYI",
        "origin_title": "Tổng tài uống rượu siêu cuốn #Nửalàđườngmậtnửalàđauthương #LaVânHi #BạchLộc #iQIYI",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "iQIYI Phim Thuyết Minh - Get the iQIYI APP",
        "poster": "https://i.ytimg.com/vi/PzM25ZtOzFo/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 668100,
        "likes": 14256,
        "comments_count": 572,
        "caption": "Tổng tài uống rượu siêu cuốn #Nửalàđườngmậtnửalàđauthương #LaVânHi #BạchLộc #iQIYI - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_qfJUsASeyIU",
        "yt": "qfJUsASeyIU",
        "title": "Phim Hay Trích Đoạn hay  ngan  Bo #Xuhuong #TrichDoanPhim",
        "origin_title": "Phim Hay Trích Đoạn hay  ngan  Bo #Xuhuong #TrichDoanPhim",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Kịch Ngắn Đỉnh Cao",
        "poster": "https://i.ytimg.com/vi/qfJUsASeyIU/hqdefault.jpg",
        "year": "2026",
        "rating": "4.9",
        "views": 349857,
        "likes": 65273,
        "comments_count": 1039,
        "caption": "Phim Hay Trích Đoạn hay  ngan  Bo #Xuhuong #TrichDoanPhim - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_Z4A0K8EG-II",
        "yt": "Z4A0K8EG-II",
        "title": "Phim Hay Trích Đoạn hay  ngan  Bo #Xuhuong #TrichDoanPhim",
        "origin_title": "Phim Hay Trích Đoạn hay  ngan  Bo #Xuhuong #TrichDoanPhim",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Kịch Ngắn Đỉnh Cao",
        "poster": "https://i.ytimg.com/vi/Z4A0K8EG-II/hqdefault.jpg",
        "year": "2026",
        "rating": "4.7",
        "views": 729617,
        "likes": 41459,
        "comments_count": 1157,
        "caption": "Phim Hay Trích Đoạn hay  ngan  Bo #Xuhuong #TrichDoanPhim - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_LobsZtgN3pA",
        "yt": "LobsZtgN3pA",
        "title": "Đỉnh cao võ thuật! 🥋🔥 #film#haunguyenstudio",
        "origin_title": "Đỉnh cao võ thuật! 🥋🔥 #film#haunguyenstudio",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Hậu Nguyễn Studio",
        "poster": "https://i.ytimg.com/vi/LobsZtgN3pA/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 48517,
        "likes": 59357,
        "comments_count": 572,
        "caption": "Đỉnh cao võ thuật! 🥋🔥 #film#haunguyenstudio - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_9pccz52_gLA",
        "yt": "9pccz52_gLA",
        "title": "Top 10 phim võ thuật Trung Quốc nhất định bạn phải xem  #ytshorts",
        "origin_title": "Top 10 phim võ thuật Trung Quốc nhất định bạn phải xem  #ytshorts",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Top 10 Vô Đối",
        "poster": "https://i.ytimg.com/vi/9pccz52_gLA/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 401259,
        "likes": 62295,
        "comments_count": 708,
        "caption": "Top 10 phim võ thuật Trung Quốc nhất định bạn phải xem  #ytshorts - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_w3H_yfmwOlE",
        "yt": "w3H_yfmwOlE",
        "title": "Đại Chiến Võ Thuật Cực Gắt: Đả Nữ Đơn Thương Độc Mã Hạ Gục Cả Băng Đảng | Thế Giới Phim",
        "origin_title": "Đại Chiến Võ Thuật Cực Gắt: Đả Nữ Đơn Thương Độc Mã Hạ Gục Cả Băng Đảng | Thế Giới Phim",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Thế Giới Phim",
        "poster": "https://i.ytimg.com/vi/w3H_yfmwOlE/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 70457,
        "likes": 34179,
        "comments_count": 368,
        "caption": "Đại Chiến Võ Thuật Cực Gắt: Đả Nữ Đơn Thương Độc Mã Hạ Gục Cả Băng Đảng | Thế Giới Phim - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_Zsa0tvB19qg",
        "yt": "Zsa0tvB19qg",
        "title": "Màn võ thuật đỉnh cao một mình hạ gục cả băng nhóm cực ngầu! 🎬🔥  #Action #Combat",
        "origin_title": "Màn võ thuật đỉnh cao một mình hạ gục cả băng nhóm cực ngầu! 🎬🔥  #Action #Combat",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Hậu Nguyễn Studio",
        "poster": "https://i.ytimg.com/vi/Zsa0tvB19qg/hqdefault.jpg",
        "year": "2026",
        "rating": "4.9",
        "views": 311983,
        "likes": 102046,
        "comments_count": 900,
        "caption": "Màn võ thuật đỉnh cao một mình hạ gục cả băng nhóm cực ngầu! 🎬🔥  #Action #Combat - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_FPXq0i71-KI",
        "yt": "FPXq0i71-KI",
        "title": "Tuyệt kỹ võ thuật đỉnh cao chốn thâm sơn! 🎬🔥  #Kungfu #Vothuat #TrendingShorts",
        "origin_title": "Tuyệt kỹ võ thuật đỉnh cao chốn thâm sơn! 🎬🔥  #Kungfu #Vothuat #TrendingShorts",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Hậu Nguyễn Studio",
        "poster": "https://i.ytimg.com/vi/FPXq0i71-KI/hqdefault.jpg",
        "year": "2026",
        "rating": "4.7",
        "views": 430449,
        "likes": 54521,
        "comments_count": 1327,
        "caption": "Tuyệt kỹ võ thuật đỉnh cao chốn thâm sơn! 🎬🔥  #Kungfu #Vothuat #TrendingShorts - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_DJ7cOjSC8E4",
        "yt": "DJ7cOjSC8E4",
        "title": "Võ Thuật Đỉnh Cao Tony Jaa | Tony Jaa Fight Scene Martial Arts | Best Fighting Scenes",
        "origin_title": "Võ Thuật Đỉnh Cao Tony Jaa | Tony Jaa Fight Scene Martial Arts | Best Fighting Scenes",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Huy Hoàngg",
        "poster": "https://i.ytimg.com/vi/DJ7cOjSC8E4/hqdefault.jpg",
        "year": "2026",
        "rating": "4.7",
        "views": 599127,
        "likes": 89095,
        "comments_count": 550,
        "caption": "Võ Thuật Đỉnh Cao Tony Jaa | Tony Jaa Fight Scene Martial Arts | Best Fighting Scenes - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_fVxHsGZNawQ",
        "yt": "fVxHsGZNawQ",
        "title": "Mỹ Nữ Trình Diễn Võ Thuật Đỉnh Cao - Nghệ Thuật Và Sức Mạnh Kết Hợp",
        "origin_title": "Mỹ Nữ Trình Diễn Võ Thuật Đỉnh Cao - Nghệ Thuật Và Sức Mạnh Kết Hợp",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Thuận Blog",
        "poster": "https://i.ytimg.com/vi/fVxHsGZNawQ/hqdefault.jpg",
        "year": "2026",
        "rating": "4.9",
        "views": 454792,
        "likes": 77383,
        "comments_count": 1298,
        "caption": "Mỹ Nữ Trình Diễn Võ Thuật Đỉnh Cao - Nghệ Thuật Và Sức Mạnh Kết Hợp - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_QnXmKPXYHFA",
        "yt": "QnXmKPXYHFA",
        "title": "\"Cao Thủ Võ Thuật Thể Hiện Kỹ Năng Đỉnh Cao#movie #film #funny #kungfu #vothuattonghop",
        "origin_title": "\"Cao Thủ Võ Thuật Thể Hiện Kỹ Năng Đỉnh Cao#movie #film #funny #kungfu #vothuattonghop",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Hậu Nguyễn Studio",
        "poster": "https://i.ytimg.com/vi/QnXmKPXYHFA/hqdefault.jpg",
        "year": "2026",
        "rating": "5.0",
        "views": 696450,
        "likes": 70747,
        "comments_count": 975,
        "caption": "\"Cao Thủ Võ Thuật Thể Hiện Kỹ Năng Đỉnh Cao#movie #film #funny #kungfu #vothuattonghop - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_LuZlwUytulM",
        "yt": "LuZlwUytulM",
        "title": "💦Đỉnh cao võ thuật Thiếu Lâm – Màn biểu diễn cực chất của Lý Huyền Phong #kungfu",
        "origin_title": "💦Đỉnh cao võ thuật Thiếu Lâm – Màn biểu diễn cực chất của Lý Huyền Phong #kungfu",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "music - remix",
        "poster": "https://i.ytimg.com/vi/LuZlwUytulM/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 456146,
        "likes": 54809,
        "comments_count": 836,
        "caption": "💦Đỉnh cao võ thuật Thiếu Lâm – Màn biểu diễn cực chất của Lý Huyền Phong #kungfu - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_XAsdgSRa1hs",
        "yt": "XAsdgSRa1hs",
        "title": "Khi cao thủ đọ sức một chín một mười vothuat",
        "origin_title": "Khi cao thủ đọ sức một chín một mười vothuat",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "iQIYI Movie Vietnam - Get the iQIYI APP",
        "poster": "https://i.ytimg.com/vi/XAsdgSRa1hs/hqdefault.jpg",
        "year": "2026",
        "rating": "4.6",
        "views": 653767,
        "likes": 50531,
        "comments_count": 482,
        "caption": "Khi cao thủ đọ sức một chín một mười vothuat - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_bUOxHhmkYP8",
        "yt": "bUOxHhmkYP8",
        "title": "Đỉnh cao võ học Trung Quốc - Thiếu Lâm Tự #china #kungfu #story #facts",
        "origin_title": "Đỉnh cao võ học Trung Quốc - Thiếu Lâm Tự #china #kungfu #story #facts",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Tun Tò Mò",
        "poster": "https://i.ytimg.com/vi/bUOxHhmkYP8/hqdefault.jpg",
        "year": "2026",
        "rating": "4.6",
        "views": 31909,
        "likes": 94965,
        "comments_count": 995,
        "caption": "Đỉnh cao võ học Trung Quốc - Thiếu Lâm Tự #china #kungfu #story #facts - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_HobNWES_KtU",
        "yt": "HobNWES_KtU",
        "title": "Cao thủ thách đấu Mã Vĩnh Trinh  phim hành động võ thuật hay nhất",
        "origin_title": "Cao thủ thách đấu Mã Vĩnh Trinh  phim hành động võ thuật hay nhất",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "BH Entertainment",
        "poster": "https://i.ytimg.com/vi/HobNWES_KtU/hqdefault.jpg",
        "year": "2026",
        "rating": "4.9",
        "views": 680586,
        "likes": 56559,
        "comments_count": 1190,
        "caption": "Cao thủ thách đấu Mã Vĩnh Trinh  phim hành động võ thuật hay nhất - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_1Lm2-1boeTw",
        "yt": "1Lm2-1boeTw",
        "title": "Đỉnh cao của võ thuật",
        "origin_title": "Đỉnh cao của võ thuật",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Vũ mạnh long",
        "poster": "https://i.ytimg.com/vi/1Lm2-1boeTw/hqdefault.jpg",
        "year": "2026",
        "rating": "4.9",
        "views": 354027,
        "likes": 93853,
        "comments_count": 593,
        "caption": "Đỉnh cao của võ thuật - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_0IbzaP9T3Vk",
        "yt": "0IbzaP9T3Vk",
        "title": "Chàng Trai Ngày Đêm Khổ Luyện Đưa Võ Thuật Trung Hoa Lên Đỉnh Cao hanhdong phim",
        "origin_title": "Chàng Trai Ngày Đêm Khổ Luyện Đưa Võ Thuật Trung Hoa Lên Đỉnh Cao hanhdong phim",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Tâm Review",
        "poster": "https://i.ytimg.com/vi/0IbzaP9T3Vk/hqdefault.jpg",
        "year": "2026",
        "rating": "4.9",
        "views": 734462,
        "likes": 80094,
        "comments_count": 1217,
        "caption": "Chàng Trai Ngày Đêm Khổ Luyện Đưa Võ Thuật Trung Hoa Lên Đỉnh Cao hanhdong phim - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_r5EIrjwD0MU",
        "yt": "r5EIrjwD0MU",
        "title": "Phim Kiếm Hiệp Đánh Nhau Cực Căng |  2024",
        "origin_title": "Phim Kiếm Hiệp Đánh Nhau Cực Căng |  2024",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Clip Phim Trung Quoc",
        "poster": "https://i.ytimg.com/vi/r5EIrjwD0MU/hqdefault.jpg",
        "year": "2026",
        "rating": "4.9",
        "views": 570788,
        "likes": 62514,
        "comments_count": 271,
        "caption": "Phim Kiếm Hiệp Đánh Nhau Cực Căng |  2024 - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_nACwnD0nyWc",
        "yt": "nACwnD0nyWc",
        "title": "Top Những Pha Võ Thuật Đỉnh Cao Trong Phim Hành Động| Funny Martiral Arts - FMA",
        "origin_title": "Top Những Pha Võ Thuật Đỉnh Cao Trong Phim Hành Động| Funny Martiral Arts - FMA",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "VOVINAM - MÃI ĐỈNH ",
        "poster": "https://i.ytimg.com/vi/nACwnD0nyWc/hqdefault.jpg",
        "year": "2026",
        "rating": "4.7",
        "views": 472969,
        "likes": 85064,
        "comments_count": 829,
        "caption": "Top Những Pha Võ Thuật Đỉnh Cao Trong Phim Hành Động| Funny Martiral Arts - FMA - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_pYLEmguFdlk",
        "yt": "pYLEmguFdlk",
        "title": "Cao thủ võ thuật solo trên võ đài  phim hành đông võ thuật hay nhất",
        "origin_title": "Cao thủ võ thuật solo trên võ đài  phim hành đông võ thuật hay nhất",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "BH Entertainment",
        "poster": "https://i.ytimg.com/vi/pYLEmguFdlk/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 452709,
        "likes": 30417,
        "comments_count": 758,
        "caption": "Cao thủ võ thuật solo trên võ đài  phim hành đông võ thuật hay nhất - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_cVoluvXmU_c",
        "yt": "cVoluvXmU_c",
        "title": "Mãn nhãn màn võ thuật đỉnh cao trong phim hành động | Action Scene 💥 #movie ngan #film #funny",
        "origin_title": "Mãn nhãn màn võ thuật đỉnh cao trong phim hành động | Action Scene 💥 #movie ngan #film #funny",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Hậu Nguyễn Studio",
        "poster": "https://i.ytimg.com/vi/cVoluvXmU_c/hqdefault.jpg",
        "year": "2026",
        "rating": "4.7",
        "views": 443201,
        "likes": 17718,
        "comments_count": 310,
        "caption": "Mãn nhãn màn võ thuật đỉnh cao trong phim hành động | Action Scene 💥 #movie ngan #film #funny - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_ooLDgwuM4SA",
        "yt": "ooLDgwuM4SA",
        "title": "Cao thủ miền tây đánh võ cực đỉnh  phim hành động hay",
        "origin_title": "Cao thủ miền tây đánh võ cực đỉnh  phim hành động hay",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "BH Entertainment",
        "poster": "https://i.ytimg.com/vi/ooLDgwuM4SA/hqdefault.jpg",
        "year": "2026",
        "rating": "4.7",
        "views": 827016,
        "likes": 89879,
        "comments_count": 892,
        "caption": "Cao thủ miền tây đánh võ cực đỉnh  phim hành động hay - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v__w2O3R3NIAw",
        "yt": "_w2O3R3NIAw",
        "title": "Một Mình Cân Tất: Đẳng Cấp Võ Thuật Đỉnh Cao! 🔥  #film #martialarts",
        "origin_title": "Một Mình Cân Tất: Đẳng Cấp Võ Thuật Đỉnh Cao! 🔥  #film #martialarts",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Hậu Nguyễn Studio",
        "poster": "https://i.ytimg.com/vi/_w2O3R3NIAw/hqdefault.jpg",
        "year": "2026",
        "rating": "4.9",
        "views": 324201,
        "likes": 55301,
        "comments_count": 514,
        "caption": "Một Mình Cân Tất: Đẳng Cấp Võ Thuật Đỉnh Cao! 🔥  #film #martialarts - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_qm9AgjDyo8k",
        "yt": "qm9AgjDyo8k",
        "title": "Top 10 diễn viên võ thuật Trung Quốc có khả năng thực chiến mạnh nhất #khampha #top10 #vothuat",
        "origin_title": "Top 10 diễn viên võ thuật Trung Quốc có khả năng thực chiến mạnh nhất #khampha #top10 #vothuat",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Người kể chuyện",
        "poster": "https://i.ytimg.com/vi/qm9AgjDyo8k/hqdefault.jpg",
        "year": "2026",
        "rating": "4.7",
        "views": 750602,
        "likes": 101559,
        "comments_count": 683,
        "caption": "Top 10 diễn viên võ thuật Trung Quốc có khả năng thực chiến mạnh nhất #khampha #top10 #vothuat - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_dKohcRgmevM",
        "yt": "dKohcRgmevM",
        "title": "Cao thủ solo võ sĩ tây  phim hành động 2024",
        "origin_title": "Cao thủ solo võ sĩ tây  phim hành động 2024",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "BH Entertainment",
        "poster": "https://i.ytimg.com/vi/dKohcRgmevM/hqdefault.jpg",
        "year": "2026",
        "rating": "4.7",
        "views": 459453,
        "likes": 75169,
        "comments_count": 772,
        "caption": "Cao thủ solo võ sĩ tây  phim hành động 2024 - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_Vo1NFs7jxfE",
        "yt": "Vo1NFs7jxfE",
        "title": "Top 10 Phim Hành Động Võ Thuật Đỉnh Cao   hành động  võ thuật #võ thuật #top #top10",
        "origin_title": "Top 10 Phim Hành Động Võ Thuật Đỉnh Cao   hành động  võ thuật #võ thuật #top #top10",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Lời Kể Từ Bóng Tối",
        "poster": "https://i.ytimg.com/vi/Vo1NFs7jxfE/hqdefault.jpg",
        "year": "2026",
        "rating": "5.0",
        "views": 834727,
        "likes": 74579,
        "comments_count": 995,
        "caption": "Top 10 Phim Hành Động Võ Thuật Đỉnh Cao   hành động  võ thuật #võ thuật #top #top10 - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_Hb_xBAS6Uk0",
        "yt": "Hb_xBAS6Uk0",
        "title": "NHẤT KIẾM PHỤ TÌNH - Tập Cuối",
        "origin_title": "NHẤT KIẾM PHỤ TÌNH - Tập Cuối",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Oppa Huy IDol",
        "poster": "https://i.ytimg.com/vi/Hb_xBAS6Uk0/hqdefault.jpg",
        "year": "2026",
        "rating": "4.8",
        "views": 229761,
        "likes": 75261,
        "comments_count": 1284,
        "caption": "NHẤT KIẾM PHỤ TÌNH - Tập Cuối - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    },
    {
        "id": "reel_v_FKGhEWdohQg",
        "yt": "FKGhEWdohQg",
        "title": "Muay Thái của Tony Jaa thực sự mạnh như thế nào?",
        "origin_title": "Muay Thái của Tony Jaa thực sự mạnh như thế nào?",
        "slug": "phim-hot",
        "type": "reel",
        "aspect": "9:16",
        "author": "Koha Discovery",
        "poster": "https://i.ytimg.com/vi/FKGhEWdohQg/hqdefault.jpg",
        "year": "2026",
        "rating": "4.7",
        "views": 327708,
        "likes": 41388,
        "comments_count": 701,
        "caption": "Muay Thái của Tony Jaa thực sự mạnh như thế nào? - Siêu phẩm trích đoạn phim ngắn cực cuốn trên APhim Super.",
        "categories": [
            "Hành Động",
            "Phim Ngắn",
            "Hot Trend"
        ]
    }
]
};
